<h1>An Error Occurred:</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
        <hr/>
        <h2>Additional information:</h2>

        <h3><?php echo get_class($this->exception); ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums">
                    <?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?>
                </pre>
            </dd>

            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
            </dd>

            <dt>Stack Trace:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
            </dd>
        </dl>
    <?php else: ?>
        <h3>No Exception available</h3>
    <?php endif ?>
<?php endif ?>
