<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="make a mandala coloring book online">
    <?= $this->placeholder('meta') ?>
    <?= $this->headTitle() ?>

    <link href="/lib/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/lib/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/lib/jquery-ui/css/smoothness/jquery-ui-1.10.3.custom.min.css" />
    <link rel="stylesheet" href="/css/main.css" type="text/css" media="screen">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    The Mandala Book
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?= $this->url('all-designs') ?>">Designs</a></li>
                    <li><a href="<?= $this->url('books') ?>">Books</a></li>
                    <li>
                        <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=35BS6JPKESKW6">
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            Donate
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right" style="margin-left: 0">
                    <form>
                        <? if ($currentUser->isAnonymous()): ?>
                            <li>
                                <a class="btn btn-primary navbar-btn" data-toggle="modal" id="sign-in-button" href="<?= $this->url('sign-in') ?>">
                                    Sign In
                                </a>
                            </li>
                        <? else: ?>
                            <li>
                                <span class="hidden-xs hidden-sm pull-left navbar-text" style="color: #777777; font-size: 16px; margin-right: 0.5em"><?=
                                    $this->escapeHtml($currentUser->email) ?></span>
                                <img src="https://www.gravatar.com/avatar/<?= md5($currentUser->email) ?>?s=32" />
                                <a class="btn btn-default navbar-btn" id="sign-out-button" href="<?= $this->url('sign-out') ?>">
                                    Sign Out
                                </a>
                            </li>
                        <? endif ?>
                    </form>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <?= $this->content ?>
        </div>
    </div>

    <div id="footer">
        <div class="container">
            <p class="text-muted credit text-center">
                &copy; <a href="http://brady.lucidgene.com/">Brady Olsen</a>.
                View the source code on <a href="https://github.com/bradyo/mandala-book">GitHub</a>.
            </p>
        </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="/lib/jquery.touch-punch.min.js"></script>
    <script src="/lib/jquery.ba-resize.min.js"></script>
    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="/lib/raphael-min.js"></script>
    <script src="/lib/raphael.export.js"></script>
    <script src="/js/main.js"></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-47732510-1', 'mandalabook.com');
        ga('send', 'pageview');
    </script>
    <?= $this->userEchoWidget() ?>
    <?= $this->placeholder('scripts') ?>
</body>
</html>
