<script type='text/javascript'>

    var _ues = {
        host:'mandalabook.userecho.com',
        forum:'30796',
        lang:'en',
        tab_corner_radius:5,
        tab_font_size:20,
        tab_image_hash:'R2l2ZSBGZWVkYmFjaw%3D%3D',
        tab_chat_hash:'U3VwcG9ydA%3D%3D',
        tab_alignment:'right',
        tab_text_color:'#FFFFFF',
        tab_text_shadow_color:'#00000055',
        tab_bg_color:'#2B669A',
        tab_hover_color:'#428BCA'
    };

    (function() {
        var _ue = document.createElement('script'); _ue.type = 'text/javascript'; _ue.async = true;
        _ue.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.userecho.com/js/widget-1.4.gz.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(_ue, s);
    })();

</script>