<div class="jumbotron">
    <h1 class="text-center">Welcome to the Mandala Book!</h1>

    <hr />
    <p>The Mandala Book allows you to create awesome coloring book designs and share them online.</p>
    <ul>
        <li>Make a custom gift for your kids, girlfriend, grandparents, and other loved ones</li>
        <li>Relax after a long days work in your favorite chair to color some entrancing designs</li>
        <li>Reduce stress through drawing</li>
        <li>Share your favorite designs with friends</li>
    </ul>

    <p class="text-center" style="margin: 1em 0"><img src="/img/sample-designs.png" /></p>

    <div class="text-center">
        <p>Start creating some designs today for free, no sign-up required!</p>
        <p>
            <a class="btn btn-lg btn-primary btn-wide" href="<?= $this->url('all-designs') ?>" role="button">Browse Designs</a>
            <a class="btn btn-lg btn-primary btn-wide" href="<?= $this->url('new-design') ?>" role="button">Create a Design</a>
        </p>
    </div>
</div>