<?
/**
 * @var $type string
 */
?>
<div class="alert alert-info" style="overflow: hidden">
    <a class="btn btn-primary btn-wide pull-right" href="<?= $this->url('create-order', array('type' => $type)) ?>">
        Buy a Book
    </a>
    <p style="line-height: 2.2em; height: 2em; vertical-align: middle;">
        Want a high-quality copy of these designs delivered to you by mail or e-mail?</p>
</div>