<div class="jumbotron">
    <h1 class="text-center">Welcome to the Mandala Book!</h1>

    <hr />

    <div style="max-width: 800px; margin: 1em auto;">
        <p>The Mandala Book allows you to create awesome coloring book designs and share them online.</p>
        <ul>
            <li>Make a custom coloring book gift for your kids and loved ones</li>
            <li>Relax after a long days work in your favorite chair and color designs</li>
            <li>Reduce stress through meditative coloring</li>
            <li>Share your favorite designs with friends</li>
        </ul>
    </div>


    <p class="text-center" style="margin: 1em 0"><img src="/img/sample-designs.png" /></p>

    <div class="text-center">
        <p>Start creating some designs today, no sign-up required!</p>
        <p>
            <a class="btn btn-lg btn-primary btn-wide" href="<?= $this->url('all-designs') ?>">Browse Designs</a>
            <a class="btn btn-lg btn-primary btn-wide" href="<?= $this->url('new-design') ?>">Create a Design</a>
        </p>
    </div>
</div>