<div class="col-md-3">
    <?= $this->partial('book-module/sidebar-menu.phtml', array('route' => 'books')) ?>

    <div class="sidebar-gutter hidden-sm hidden-xs">
        <?= $this->tallAd() ?>
    </div>
</div>

<div class="col-md-9">
    <?= $this->partial('book-module/books.phtml', array(
        'books' => $books,
        'pager' => $pager,
        'route' => 'user-favorite-books'
    )) ?>

    <? if (count($books) == 0): ?>
        <div class="alert alert-warning">
            You don't have any favorites books yet!
            <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('books') ?>">Find Some</a>
        </div>
    <? endif ?>

    <div class="bottom-gutter visible-sm visible-xs">
        <?= $this->shortAd() ?>
    </div>
</div>
