<?
/**
 * @var \Mandala\UserModule\User $currentUser
 * @var array $designs
 * @var \Zend\Paginator\Paginator $pager
 */
?>
<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('design-module/sidebar.phtml', array(
        'user' => $currentUser,
        'route' => 'favorite-designs'
    )) ?>

    <? if (count($designs) > 0): ?>
        <div style="margin-bottom: 1em">
            <?= $this->facebookShareButton(array(
                'link' => $this->url('favorite-designs', array('userId' => $currentUser->id), array('force_canonical' => true)),
                'name' => 'Mandala Book Designs',
                'description' => 'Check out these awesome mandala designs',
                'picture' => $this->url('get-design-thumbnail', array('id' => $designs[0]->id, 'size' => '1200'), array('force_canonical' => true))
            )) ?>
        </div>
    <? endif ?>

    <?= $this->tallAd() ?>
</div>

<div class="filler">
    <?= $this->partial('design-module/designs.phtml', array(
        'currentUser' => $currentUser,
        'designs' => $designs,
        'pager' => $pager,
        'route' => 'favorite-designs',
        'sort' => $sort,
        'showBooksToolbar' => $showBooksToolbar,
        'showBooksToolbarHelp' => $showBooksToolbarHelp
    )) ?>

    <? if (count($designs) == 0): ?>
        <div class="alert alert-warning">
            You have no favorite designs yet!
            <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('all-designs') ?>">Find some now</a>
        </div>
    <? endif ?>
</div>
