<?
/**
 * @var \Mandala\UserModule\User $currentUser
 * @var array $designs
 * @var \Zend\Paginator\Paginator $pager
 */
?>
<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('design-module/sidebar.phtml', array(
        'user' => $currentUser,
        'route' => 'all-designs'
    )) ?>

    <div style="margin-bottom: 1em">
        <?= $this->facebookShareButton(array(
            'link' => $this->url('all-designs', array(), array('force_canonical' => true)),
            'name' => 'Mandala Book Designs',
            'description' => 'Check out these awesome mandala designs',
            'picture' => $this->url('get-design-thumbnail', array('id' => $designs[0]->id, 'size' => '1200'), array('force_canonical' => true))
        )) ?>
    </div>

    <?= $this->render('design-module/ads.phtml') ?>
</div>

<div class="filler">
    <?= $this->partial('design-module/designs.phtml', array(
        'route' => 'all-designs',
        'currentUser' => $currentUser,
        'designs' => $designs,
        'pager' => $pager,
    )) ?>
</div>