<div class="sidebar col-md-3">
    <?= $this->partial('design-module/sidebar.phtml', array('route' => 'all-designs')) ?>

    <div class="sidebar-gutter hidden-sm hidden-xs">
        <?= $this->tallAd() ?>
    </div>
</div>

<div class="content col-md-9">
    <?= $this->partial('design-module/designs.phtml', array(
        'sort' => $sort,
        'route' => $route,
        'currentUser' => $currentUser,
        'designs' => $designs,
        'pager' => $pager,
        'showBooksToolbar' => $showBooksToolbar,
        'showBooksToolbarHelp' => $showBooksToolbarHelp
    )) ?>

    <div class="bottom-gutter visible-sm visible-xs">
        <?= $this->shortAd() ?>
    </div>
</div>
