<div class="sidebar col-md-3">
    <?= $this->partial('design-module/sidebar.phtml', array('route' => 'new-design' )) ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Design Options</h3>
        </div>
        <div class="panel-body">
            <div id="controls">
                <div class="form-group">
                    <label for="shape-type-control">Layers</label>
                    <div id="layers">
                        <?php $layers = json_decode($design->data) ?>
                        <?php for ($i = 0; $i < count($layers); $i++): ?>
                            <div id="layer-<?= $i ?>" class="layer"></div>
                        <?php endfor ?>
                        <div id="add-layer" class="layer">+</div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="shape-type-control">Shape Type</label>
                    <select id="shape-type-control" class="form-control" style="width:100%">
                        <option value="circle">Circle</option>
                        <option value="triangle">Triangle</option>
                        <option value="square">Square</option>
                        <option value="diamond">Diamond</option>
                        <option value="star">Star</option>
                        <option value="heart">Heart</option>
                        <option value="leaf">Leaf</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="shape-size-control">Shape Size</label>
                    <div id="shape-size-control"></div>
                </div>
                <div class="form-group">
                    <label for="shape-count-control">Shape Count</label>
                    <div id="shape-count-control"></div>
                </div>
                <div class="form-group">
                    <label for="displacement-control">Displacement</label>
                    <div id="displacement-control"></div>
                </div>
                <div class="form-group">
                    <label for="angle-offset-control">Angle Offset</label>
                    <div id="angle-offset-control"></div>
                </div>
                <div class="form-group">
                    <label for="rotation-control">Rotation</label>
                    <div id="rotation-control"></div>
                </div>
            </div>

            <form id="save-form" method="post">
                <input type="hidden" id="design-data" name="data">
                <input type="submit" name="submit-button" class="btn btn-block btn-primary" value="Save" />
            </form>
        </div>
    </div>
</div>

<div class="content col-md-9">
    <div id="canvas"></div>
</div>

<?php $this->placeholder('scripts')->captureStart() ?>
    <script>
        var canvas = makeCanvas('canvas');
        var design = JSON.parse('<?= $design->toJson() ?>');
        var layers = design.layers;
        var defaultLayer = $.extend({}, layers[0]);
        var layerCount = layers.length;
        var currentLayerIndex = 0;

        function update() {
            $('#design-data').val(JSON.stringify(layers));
            drawDesign(canvas, design, currentLayerIndex);
        }

        function selectLayer(id) {
            currentLayerIndex = id;
            $('#layers').find('.layer').removeClass('selected');
            $('#layer-' + id).addClass('selected');
            $('#shape-type-control').val(layers[currentLayerIndex].shapeType).change();
            $('#shape-size-control').slider('value', layers[currentLayerIndex].shapeSize);
            $('#shape-count-control').slider('value', layers[currentLayerIndex].shapeCount);
            $('#displacement-control').slider('value', layers[currentLayerIndex].displacement);
            $('#angle-offset-control').slider('value', layers[currentLayerIndex].angleOffset);
            $('#rotation-control').slider('value', layers[currentLayerIndex].rotation);
            update();
        }

        function initLayer(id) {
            $('#layer-' + id).click(function() {
                selectLayer(id);
            });
        }

        function addLayer() {
            var id = layerCount;
            $('#add-layer').before(
                '<div id="layer-' + id + '" class="layer"></div>'
            );
            layers[id] = $.extend({}, defaultLayer);
            layerCount++;
            initLayer(id);
            selectLayer(id);
        }

        $(window).resize(function() {
            var canvasElement = $('#canvas');
            var maxSize = $(this).height() - 80;
            canvasElement.css('height', canvasElement.css('width'));
            canvasElement.css('max-height', maxSize);
            canvasElement.css('max-width', maxSize);
            drawDesign(canvas, design, currentLayerIndex);
        });

        jQuery(document).ready(function() {
            for (var id = 0; id < layerCount; id++) {
                console.log('initLayer(' + id + ') called');
                initLayer(id);
            }

            $('#add-layer').click(function() {
                addLayer();
            });

            $('#shape-type-control').change(function() {
                layers[currentLayerIndex].shapeType = $('#shape-type-control').val();
                update();
            });

            $('#shape-size-control').slider({
                value: 40,
                max: 300,
                step: 5,
                slide: function(event, ui) {
                    layers[currentLayerIndex].shapeSize = ui.value;
                    update();
                }
            });

            $('#shape-count-control').slider({
                value: 6,
                max: 20,
                slide: function(event, ui) {
                    layers[currentLayerIndex].shapeCount = ui.value;
                    update();
                }
            });

            $('#displacement-control').slider({
                value: 50,
                max: 600,
                slide: function(event, ui) {
                    layers[currentLayerIndex].displacement = ui.value;
                    update();
                }
            });

            $('#angle-offset-control').slider({
                max: 360,
                slide: function(event, ui) {
                    layers[currentLayerIndex].angleOffset = ui.value;
                    update();
                }
            });

            $('#rotation-control').slider({
                max: 360,
                slide: function(event, ui) {
                    layers[currentLayerIndex].rotation = ui.value;
                    update();
                }
            });

            selectLayer(0);
            update();
        });
    </script>
<?php $this->placeholder('scripts')->captureEnd() ?>

