<?
/**
 * @var \Mandala\UserModule\User $currentUser
 * @var \Mandala\DesignModule\Design $design
 */
?>
<style type="text/css">
    @media print {
        #main-content {
            width: 100%;
        }
        #viewport {
            width: 720px; margin: 0 auto;
        }
        #canvas {
            background: none;
            border: none;
        }
        .navbar { display: none }
        #sidebar { display: none }
        #footer { display: none }
        .ue-tab-container { display: none }
        .disqus { display: none }
    }
</style>

<? $this->placeholder('meta')->captureStart() ?>
    <meta property="og:type" content="article" />
    <meta property="og:image" content="<?= $this->url('get-design-thumbnail', array('id' => $design->id, 'size' => 1200),
        array('force_canonical' => true)) ?>" />
<? $this->placeholder('meta')->captureEnd() ?>

<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('design-module/sidebar.phtml', array(
        'user' => $currentUser,
        'route' => 'show-design'
    )) ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Design Actions</h3>
        </div>
        <div class="panel-body">
            <? $removeFavoriteHtml = '<span class="glyphicon glyphicon-heart"></span> Remove Favorite' ?>
            <? $addFavoriteHtml = '<span class="glyphicon glyphicon-heart-empty"></span> Add to Favorites' ?>
            <button id="favorite-button" class="btn btn-default btn-block <?= $isFavorite ? 'favorited' : '' ?>">
                <?= $isFavorite ? $removeFavoriteHtml : $addFavoriteHtml ?>
            </button>
            <? $this->placeholder('scripts')->captureStart() ?>
                <script>
                    $(document).ready(function() {
                        $('#favorite-button').click(function() {
                            var postUrl;
                            if ($("#favorite-button").hasClass('favorited')) {
                                // remove and set button back to add
                                postUrl = "<?= $this->url('remove-favorite-design') ?>";
                                $("#favorite-button").removeClass("favorited");
                                $("#favorite-button").html('<?= $addFavoriteHtml ?>');
                                $("#favorited-count").html(parseInt($("#favorited-count").html()) - 1);
                            } else {
                                postUrl = "<?= $this->url('add-favorite-design') ?>";
                                $("#favorite-button").addClass("favorited");
                                $("#favorite-button").html('<?= $removeFavoriteHtml ?>');
                                $("#favorited-count").html(parseInt($("#favorited-count").html()) + 1);
                            }
                            $.ajax({
                                url: postUrl,
                                type: "POST",
                                data: {
                                    id: <?= $design->id ?>
                                },
                                dataType: "html"
                            });
                        });
                    })
                </script>
            <? $this->placeholder('scripts')->captureEnd() ?>

            <button id="print-button" class="btn btn-default btn-block">
                <span class="glyphicon glyphicon-print"></span>
                Print Design
            </button>
            <? $this->placeholder('scripts')->captureStart() ?>
                <script>
                    $(document).ready(function() {
                        $('#print-button').click(function() {
                            window.print();
                        });
                    });
                </script>
            <? $this->placeholder('scripts')->captureEnd() ?>

            <? if ($isOwner): ?>
                <a class="btn btn-block btn-default" data-toggle="modal" data-target="#confirm-delete-modal">
                    <span class="glyphicon glyphicon-remove"></span>
                    Delete Design
                </a>
                <form action="<?= $this->url('delete-design', array('id' => $design->id)) ?>" method="post">
                    <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="confirm-delete-modal-label">Confirm Delete</h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this awesome design?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="submit" class="btn btn-primary" value="Delete Design" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <? endif ?>
        </div>
    </div>

    <div style="margin-bottom: 1em">
        <?= $this->facebookShareButton(array(
            'link' => $this->serverUrl(true),
            'name' => 'Mandala Book Design',
            'description' => 'Check out this awesome mandala design',
            'picture' => $this->url('get-design-thumbnail', array('id' => $design->id, 'size' => '1200'), array('force_canonical' => true))
        )) ?>
    </div>

    <?= $this->shortAd() ?>
</div>

<div id='main-content' class="col-md-9">
    <div id="viewport">
        <div id="canvas" style="margin-bottom: 1em"></div>

        <div class="disqus panel panel-default" style="width: 720px; margin-bottom: 1em">
            <div class="panel-body">
                <?= $this->disqus() ?>
            </div>
        </div>
    </div>
</div>

<?php $this->placeholder('scripts')->captureStart() ?>
    <script>
        var canvasWidth = 720;
        var canvasHeight = 720;
        var canvas = new Raphael('canvas', canvasWidth, canvasHeight);
        var layers = JSON.parse('<?php echo $design->data ?>');

        jQuery(document).ready(function() {
            drawDesign(canvas, layers);
        });
    </script>
<?php $this->placeholder('scripts')->captureEnd() ?>

