<?
/**
 * @var \Mandala\UserModule\User $currentUser
 * @var \Mandala\DesignModule\Design $design
 */
?>
<style type="text/css">
    @media print {
        .navbar { display: none }
        #sidebar { display: none }
        #footer { display: none }
    }
</style>

<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('design-module/sidebar.phtml', array(
        'user' => $currentUser,
        'route' => 'show-design'
    )) ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">This Design</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <? $removeFavoriteHtml = '<span class="glyphicon glyphicon-heart"></span> Remove Favorite' ?>
                <? $addFavoriteHtml = '<span class="glyphicon glyphicon-heart-empty"></span> Add to Favorites' ?>
                <button id="favorite-button" class="btn btn-default btn-block <?= $isFavorite ? 'favorited' : '' ?>">
                    <?= $isFavorite ? $removeFavoriteHtml : $addFavoriteHtml ?>
                </button>
                <? $this->placeholder('scripts')->captureStart() ?>
                    <script>
                        $(document).ready(function() {
                            $('#favorite-button').click(function() {
                                var postUrl;
                                if ($("#favorite-button").hasClass('favorited')) {
                                    // remove and set button back to add
                                    postUrl = "<?= $this->url('remove-favorite-design') ?>";
                                    $("#favorite-button").removeClass("favorited");
                                    $("#favorite-button").html('<?= $addFavoriteHtml ?>');
                                    $("#favorited-count").html(parseInt($("#favorited-count").html()) - 1);
                                } else {
                                    postUrl = "<?= $this->url('add-favorite-design') ?>";
                                    $("#favorite-button").addClass("favorited");
                                    $("#favorite-button").html('<?= $removeFavoriteHtml ?>');
                                    $("#favorited-count").html(parseInt($("#favorited-count").html()) + 1);
                                }
                                $.ajax({
                                    url: postUrl,
                                    type: "POST",
                                    data: {
                                        id: <?= $design->id ?>
                                    },
                                    dataType: "html"
                                });
                            });
                        })
                    </script>
                <? $this->placeholder('scripts')->captureEnd() ?>

                <a class="btn btn-block btn-default" role="button"
                   href="https://www.facebook.com/sharer/sharer.php?u=<?= urlencode($this->serverUrl(true)) ?>" target="_blank">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    Share on Facebook
                </a>

                <button id="print-button" class="btn btn-default btn-block">
                    <span class="glyphicon glyphicon-print"></span>
                    Print Design
                </button>
                <? $this->placeholder('scripts')->captureStart() ?>
                <script>
                    $(document).ready(function() {
                        $('#print-button').click(function() {
                            window.print();
                        });
                    });
                </script>
                <? $this->placeholder('scripts')->captureEnd() ?>
            </div>

            <div style="text-align:center">
                Favorited <span id="favorited-count"><?= $design->favoritedCount ?></span> times!
            </div>
        </div>
    </div>

    <? if ($isOwner): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Manage Design</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <a class="btn btn-block btn-default" data-toggle="modal" data-target="#confirm-delete-modal">
                        Delete
                    </a>
                    <form action="<?= $this->url('delete-design', array('id' => $design->id)) ?>" method="post">
                        <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title" id="confirm-delete-modal-label">Confirm Delete</h4>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to delete this awesome design?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        <input type="submit" class="btn btn-primary" value="Delete Design" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    <? endif ?>
</div>

<div class="col-md-9">
    <div id="viewport">
        <div id="canvas"></div>
    </div>
</div>

<?php $this->placeholder('scripts')->captureStart() ?>
    <script>
        var canvasWidth = 720;
        var canvasHeight = 720;
        var canvas = new Raphael('canvas', canvasWidth, canvasHeight);
        var layers = JSON.parse('<?php echo $design->data ?>');

        jQuery(document).ready(function() {
            drawDesign(canvas, layers);
        });
    </script>
<?php $this->placeholder('scripts')->captureEnd() ?>

