<style>
    #print-canvas {
        display: none;
    }
    @media print {
        .navbar,
        .sidebar,
        .content,
        #footer,
        .ue-tab-container {
            display: none
        }
        #print-canvas {
            width: 100%;
            display: block;
        }
    }
</style>

<img id="print-canvas" src="/data/design-files/<?= $design->id ?>.svg" alt="design-<?= $design->id ?>" />

<div class="sidebar col-md-3">
    <?= $this->partial('design-module/sidebar.phtml', array('route' => 'show-design')) ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Design Actions</h3>
        </div>
        <div class="panel-body">
            <?= $this->partial('application/favorite-button.phtml', array(
                'id' => 'favorite-button',
                'addUrl' => $this->url('add-favorite-design'),
                'removeUrl' => $this->url('remove-favorite-design'),
                'data' => array('id' => $design->id),
                'isFavorite' => $isFavorite
            )) ?>

            <?= $this->facebookShare(array(
                'link' => $this->serverUrl(true),
                'name' => 'Mandala Book Design',
                'description' => 'Check out this awesome mandala design',
                'picture' => $this->url('get-design-thumbnail', array('id' => $design->id, 'size' => '1200'), array('force_canonical' => true))
            )) ?>

            <button class="btn btn-default btn-block">
                <span class="glyphicon glyphicon-print"></span>
                Print Design
            </button>
            <? $this->placeholder('scripts')->captureStart() ?>
                <script>
                    $(document).ready(function() {
                        $('#print-button').click(function() {
                            window.print();
                        });
                    });
                </script>
            <? $this->placeholder('scripts')->captureEnd() ?>

            <? if ($isOwner): ?>
                <a class="btn btn-block btn-default" data-toggle="modal" data-target="#confirm-delete-modal">
                    <span class="glyphicon glyphicon-remove"></span>
                    Delete Design
                </a>
                <form action="<?= $this->url('delete-design', array('id' => $design->id)) ?>" method="post">
                    <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="confirm-delete-modal-label">Confirm Delete</h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this awesome design?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="submit" class="btn btn-primary" value="Delete Design" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <? endif ?>
        </div>
    </div>

    <div class="sidebar-gutter hidden-xs hidden-sm">
        <?= $this->shortAd() ?>
    </div>
</div>

<div class="content col-md-9">
    <img id="canvas" src="/data/design-files/<?= $design->id ?>.svg" alt="design-<?= $design->id ?>" />

    <?= $this->commentPanel() ?>

    <div class="bottom-gutter visible-xs visible-sm">
        <?= $this->shortAd() ?>
    </div>
</div>
