<div class="sidebar col-md-3">
    <?= $this->partial('design-module/sidebar.phtml', array('route' => 'user-designs')) ?>

    <div class="sidebar-gutter hidden-sm hidden-xs">
        <?= $this->tallAd() ?>
    </div>
</div>

<div class="content col-md-9">
    <?= $this->partial('design-module/designs.phtml', array(
        'currentUser' => $currentUser,
        'designs' => $designs,
        'pager' => $pager,
        'route' => 'user-designs',
        'sort' => $sort,
        'showBooksToolbar' => $showBooksToolbar,
        'showBooksToolbarHelp' => $showBooksToolbarHelp
    )) ?>

    <? if (count($designs) == 0): ?>
        <div class="alert alert-warning">
            You have no designs made yet!
            <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('new-design') ?>">Make one now</a>
        </div>
    <? endif ?>

    <div class="bottom-gutter visible-sm visible-xs">
        <?= $this->shortAd() ?>
    </div>
</div>
