<?
/**
 * @var array $books
 * @var \Zend\Paginator\Paginator $pager
 * @var string $route
 */
?>

<div class="item-filters">
    <?= $this->booksMenu() ?>
    <?= $this->booksSortMenu() ?>
</div>

<? if (count($books) > 0): ?>
    <div class="items">
        <? foreach ($books as $book): ?>
            <a id="book-<?= $book->id ?>" class="book-block" href="<?= $this->url('show-book', array('id' => $book->id)) ?>">
                <?= $this->escapeHtml($book->title) ?>
                <div class="book-design-count"><span id="book-<?= $book->id ?>-design-count"><?= $book->designsCount ?></span> designs</div>
            </a>
        <? endforeach ?>
    </div>
    <?= $this->paginationControl($pager, 'elastic', 'application/pagination.phtml', array('route' => $route)) ?>
<? endif ?>