<div class="list-group">
    <a href="<?= $this->url('books') ?>" class="list-group-item <?= $route == 'books' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon glyphicon-list"></span>
        Browse Books
    </a>
    <a href="<?= $this->url('new-book') ?>" class="list-group-item <?= $route == 'new-book' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-plus-sign"></span>
        New Book
    </a>
</div>
