<?php
/**
 * @var array $books
 * @var bool $showHelp
 */
?>
<? if ($showHelp): ?>
    <div class="alert alert-info">
        <button id="close-books-toolbar-help" type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <span class="glyphicon glyphicon-info-sign"></span>
        <strong>Add a design to one of your books by dragging the design into the book.</strong>
    </div>
    <? $this->placeholder('scripts')->captureStart() ?>
        <script>
            $(document).ready(function() {
                $('#close-books-toolbar-help').click(function() {
                    $.ajax({
                        url: "<?= $this->url('session-hide-books-toolbar-help') ?>",
                        type: "POST",
                        dataType: "html"
                    });
                });
            });
        </script>
    <? $this->placeholder('scripts')->captureEnd() ?>
<? endif ?>

<div class="items">
    <a class="book-block book-block-add" href="<?= $this->url('new-book') ?>">
        <span class="glyphicon glyphicon-plus-sign"></span>
        New Book
    </a>
    <? if (count($books) > 0): ?>
        <? foreach ($books as $book): ?>
            <a id="book-<?= $book->id ?>" class="book-block" href="<?= $this->url('show-book', array('id' => $book->id)) ?>">
                <?= $this->escapeHtml($book->title) ?>
                <div class="book-design-count"><span id="book-<?= $book->id ?>-design-count"><?= $book->designsCount ?></span> designs</div>
            </a>
        <? endforeach ?>
    <? endif ?>
</div>

<? $this->placeholder('scripts')->captureStart() ?>
    <script>
        $(function() {
            $(".design-block").draggable({
                revert: "invalid",
                helper: function (event) {
                    return $(this).clone().addClass("design-block-drag");
                },
                opacity: 0.5,
                cursor: 'move',
                containment: '#content'
            });
            $(".book-block").droppable({
                accept: ".design-block",
                activeClass: "book-block-active",
                hoverClass: "book-block-hover",
                drop: function(event, ui) {
                    var el = ui.draggable.clone();
                    el.appendTo($(this));
                    el.css('opacity', '1');
                    el.css('background-color', 'transparent');
                    el.fadeOut(1000);

                    var bookId = $(this).attr('id').match(/-(\d+)$/)[1];
                    var designId = ui.helper.attr('id').match(/-(\d+)$/)[1];
                    $.ajax({
                        url: "<?= $this->url('add-book-design') ?>",
                        type: "post",
                        data: {
                            bookId: bookId,
                            designId: designId
                        },
                        dataType: "html"
                    })
                    .done(function() {
                        var designCountElement = $('#book-' + bookId + '-design-count');
                        var newDesignCount = parseInt(designCountElement.html()) + 1;
                        designCountElement.html(newDesignCount);
                        console.log('design added successfully');
                    })
                    .fail(function(data, textStatus, xhr) {
                        console.log('request failed');
                        if (xhr.status == 409) {
                            console.log('design already added');
                        }
                    });
                }
            });
        });
    </script>
<? $this->placeholder('scripts')->captureEnd() ?>