<div class="cool-stuff">
    <a class="thumbnail" href="https://www.amazon.com/gp/product/B000E23RSQ/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=B000E23RSQ&linkCode=as2&tag=manda0eb-20">
        <img style="margin-top:10px" border="0" src="https://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B000E23RSQ&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=manda0eb-20" >
        <div class="caption text-center">
            Prismacolor Premier Soft Core Colored Pencils
        </div>
    </a>

    <a class="thumbnail" href="https://www.amazon.com/gp/product/B000LPJUOG/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=B000LPJUOG&linkCode=as2&tag=manda0eb-20">
        <img style="margin-top:10px" border="0" src="https://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B000LPJUOG&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=manda0eb-20" >
        <div class="caption text-center">
            Fantasia Colored Pencils in a Metal Tin
        </div>
    </a>

    <a class="thumbnail" href="https://www.amazon.com/gp/product/B001I8ZY7M/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=B001I8ZY7M&linkCode=as2&tag=manda0eb-20">
        <img style="margin-top:10px" border="0" src="https://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B001I8ZY7M&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=manda0eb-20" >
        <div class="caption text-center">
            Parchment Printing Paper
        </div>
    </a>
</div>


