<?
/**
 * @var \Mandala\UserModule\User $user
 * @var string $route
 */
?>
<div class="list-group">
    <a href="<?= $this->url('all-designs') ?>" class="list-group-item <?= $route == 'all-designs' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-globe"></span>
        Designs
    </a>
<!--    <a href="--><?//= $this->url('user-designs', array('userId' => $user->id)) ?><!--"-->
<!--        class="list-group-item --><?//= $route == 'user-designs' ? 'active' : '' ?><!--">-->
<!--        <span class="glyphicon glyphicon-pencil"></span>-->
<!--        My Designs-->
<!--    </a>-->
<!--    <a href="--><?//= $this->url('favorite-designs', array('userId' => $user->id)) ?><!--"-->
<!--        class="list-group-item --><?//= $route == 'favorite-designs' ? 'active' : '' ?><!--">-->
<!--        <span class="glyphicon glyphicon-heart"></span>-->
<!--        My Favorites-->
<!--    </a>-->
    <a href="<?= $this->url('new-design') ?>" class="list-group-item <?= $route == 'new-design' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-plus-sign"></span>
        New Design
    </a>
</div>