<?
/**
 * @var \Mandala\UserModule\User $user
 * @var string $route
 */
?>
<div class="list-group">
    <a href="<?= $this->url('all-designs') ?>" class="list-group-item <?= $route == 'all-designs' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-globe"></span>
        All Designs
    </a>
    <a href="<?= $this->url('user-designs', array('userId' => $user->id)) ?>"
        class="list-group-item <?= $route == 'user-designs' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-pencil"></span>
        My Designs
    </a>
    <a href="<?= $this->url('favorite-designs', array('userId' => $user->id)) ?>"
        class="list-group-item <?= $route == 'favorite-designs' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-heart"></span>
        My Favorites
    </a>
    <a href="<?= $this->url('new-design') ?>" class="list-group-item <?= $route == 'new-design' ? 'active' : '' ?>">
        <span class="glyphicon glyphicon-plus-sign"></span>
        New Design
    </a>
</div>

<? if (! in_array($route, array('new-design', 'show-design'))): ?>
    <div class="list-group">
        <a class="btn btn-block btn-default" role="button"
            href="https://www.facebook.com/sharer/sharer.php?u=<?= urlencode($this->serverUrl(true)) ?>" target="_blank">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Share on Facebook
        </a>
    </div>

    <div class="cool-stuff">
        <a class="thumbnail" href="http://www.amazon.com/gp/product/B000E23RSQ/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=B000E23RSQ&linkCode=as2&tag=manda0eb-20">
            <img style="margin-top:10px" border="0" src="http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B000E23RSQ&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=manda0eb-20" >
            <img src="http://ir-na.amazon-adsystem.com/e/ir?t=manda0eb-20&l=as2&o=1&a=B000E23RSQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
            <div class="caption text-center">
                Prismacolor Premier Soft Core Colored Pencils
            </div>
        </a>

        <a class="thumbnail" href="http://www.amazon.com/gp/product/B000LPJUOG/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=B000LPJUOG&linkCode=as2&tag=manda0eb-20">
            <img style="margin-top:10px" border="0" src="http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B000LPJUOG&Format=_SL160_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=manda0eb-20" >
            <img src="http://ir-na.amazon-adsystem.com/e/ir?t=manda0eb-20&l=as2&o=1&a=B000LPJUOG" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
            <div class="caption text-center">
                Fantasia Colored Pencils in a Metal Tin
            </div>
        </a>
    </div>
<? endif ?>


