<div class="sidebar col-md-3">
    <?= $this->partial('book-module/sidebar-menu.phtml', array('route' => 'books')) ?>

    <div class="sidebar-gutter hidden-sm hidden-xs">
        <?= $this->tallAd() ?>
    </div>
</div>

<div class="content col-md-9">
    <? if (count($books) > 0): ?>
        <?= $this->partial('book-module/books.phtml', array(
            'books' => $books,
            'pager' => $pager,
            'route' => 'books'
        )) ?>
    <? else: ?>
        <div class="alert alert-warning">
            You have no books made yet!
            <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('new-book') ?>">Make One</a>
        </div>
    <? endif ?>

    <div class="bottom-gutter visible-sm visible-xs">
        <?= $this->shortAd() ?>
    </div>
</div>
