<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('book-module/sidebar.phtml', array('user' => $currentUser, 'route' => 'new-book')) ?>
</div>

<div class="col-md-9">
    <h2 style="margin-top: 0">Create New Book</h2>
    <form id="new-book-form" method="post">
        <? $form->prepare() ?>
        <?= $this->formRow($form->get('token')) ?>
        <?= $this->formRow($form->get('title')) ?>
        <input class="btn btn-primary btn-wide" type="submit" value="Create Book" />
    </form>
</div>
