<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('book-module/sidebar.phtml', array('currentUser' => $currentUser, 'route' => 'show-book')) ?>
</div>

<div class="col-md-9">
    <h2 style="margin-top: 0"><?= $this->escapeHtml($book->title) ?></h2>
    <div>
        <? foreach ($book->bookDesigns as $bookDesign): ?>
            <? $design = $bookDesign->design ?>
            <a class="design-block" style="background-image:url('/data/design-files/<?= $design->id ?>-164px.png')"
               href="<?= $this->url('show-design', array('id' => $design->id)) ?>"></a>
        <? endforeach ?>

        <? if (count($book->bookDesigns) == 0): ?>
            <div class="alert alert-warning">
                This book has no designs added yet!
                <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('all-designs') ?>">Add Some Now</a>
            </div>
        <? endif ?>
    </div>
</div>
