<div class="sidebar col-md-3">
    <?= $this->partial('book-module/sidebar-menu.phtml', array('route' => 'show-book')) ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Book Actions</h3>
        </div>
        <div class="panel-body">

            <?= $this->partial('application/favorite-button.phtml', array(
                'id' => 'favorite-button',
                'addUrl' => $this->url('add-favorite-book'),
                'removeUrl' => $this->url('remove-favorite-book'),
                'data' => array('id' => $book->id),
                'isFavorite' => $isFavorite
            )) ?>

            <?= $this->facebookShare(array(
                'link' => $this->serverUrl(true),
                'name' => 'The Mandala Book',
                'description' => 'Check out this awesome mandala book',
            )) ?>

            <a class="btn btn-default btn-block" href="<?= $this->url('create-order', array('bookId' => $book->id)) ?>">
                <span class="glyphicon glyphicon-shopping-cart"></span>
                Purchase Book
            </a>

            <? if ($isOwner): ?>
                <a class="btn btn-block btn-default" data-toggle="modal" data-target="#confirm-delete-modal">
                    <span class="glyphicon glyphicon-remove"></span>
                    Delete Book
                </a>
                <form action="<?= $this->url('delete-book', array('id' => $book->id)) ?>" method="post">
                    <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="confirm-delete-modal-label">Confirm Delete</h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this awesome book?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="submit" class="btn btn-primary" value="Delete Book" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <? endif ?>
        </div>
    </div>

    <div class="sidebar-gutter hidden-xs hidden-sm">
        <?= $this->shortAd() ?>
    </div>
</div>

<div class="content col-md-9">
    <h2 style="margin-top: 0"><?= $this->escapeHtml($book->title) ?></h2>

    <? if (count($book->bookDesigns) > 0): ?>
        <div>
            <? foreach ($book->bookDesigns as $bookDesign): ?>
                <? $design = $bookDesign->design ?>
                <a class="design-block" style="background-image:url('/data/design-files/<?= $design->id ?>-164px.png')"
                   href="<?= $this->url('show-design', array('id' => $design->id)) ?>"></a>
            <? endforeach ?>
        </div>
    <? else: ?>
        <div class="alert alert-warning">
            This book has no designs added yet!
            <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('all-designs') ?>">Add Some Now</a>
        </div>
    <? endif ?>

    <div class="sidebar-gutter visible-xs visible-sm">
        <?= $this->shortAd() ?>
    </div>
</div>
