<div class="col-md-3" id="sidebar" role="navigation">
    <?= $this->partial('book-module/sidebar-menu.phtml', array('route' => 'show-book')) ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Book Actions</h3>
        </div>
        <div class="panel-body">
            <? $removeFavoriteHtml = '<span class="glyphicon glyphicon-heart"></span> Remove Favorite' ?>
            <? $addFavoriteHtml = '<span class="glyphicon glyphicon-heart-empty"></span> Add to Favorites' ?>
            <button id="favorite-button" class="btn btn-default btn-block <?= $isFavorite ? 'favorited' : '' ?>">
                <?= $isFavorite ? $removeFavoriteHtml : $addFavoriteHtml ?>
            </button>
            <? $this->placeholder('scripts')->captureStart() ?>
            <script>
                $(document).ready(function() {
                    $('#favorite-button').click(function() {
                        var postUrl;
                        if ($("#favorite-button").hasClass('favorited')) {
                            // remove and set button back to add
                            postUrl = "<?= $this->url('remove-favorite-book') ?>";
                            $("#favorite-button").removeClass("favorited");
                            $("#favorite-button").html('<?= $addFavoriteHtml ?>');
                            $("#favorited-count").html(parseInt($("#favorited-count").html()) - 1);
                        } else {
                            postUrl = "<?= $this->url('add-favorite-book') ?>";
                            $("#favorite-button").addClass("favorited");
                            $("#favorite-button").html('<?= $removeFavoriteHtml ?>');
                            $("#favorited-count").html(parseInt($("#favorited-count").html()) + 1);
                        }
                        $.ajax({
                            url: postUrl,
                            type: "POST",
                            data: {
                                id: <?= $book->id ?>
                            },
                            dataType: "html"
                        });
                    });
                })
            </script>
            <? $this->placeholder('scripts')->captureEnd() ?>

            <a id="purchase-book-button" class="btn btn-default btn-block" href="<?= $this->url('create-order', array('bookId' => $book->id)) ?>">
                <span class="glyphicon glyphicon-shopping-cart"></span>
                Purchase Book
            </a>

            <? if ($isOwner): ?>
                <a class="btn btn-block btn-default" data-toggle="modal" data-target="#confirm-delete-modal">
                    <span class="glyphicon glyphicon-remove"></span>
                    Delete Book
                </a>
                <form action="<?= $this->url('delete-book', array('id' => $book->id)) ?>" method="post">
                    <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="confirm-delete-modal-label">Confirm Delete</h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this awesome book?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="submit" class="btn btn-primary" value="Delete Book" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <? endif ?>
        </div>
    </div>

    <?= $this->shortAd() ?>
</div>

<div class="col-md-9">
    <h2 style="margin-top: 0"><?= $this->escapeHtml($book->title) ?></h2>
    <div>
        <? foreach ($book->bookDesigns as $bookDesign): ?>
            <? $design = $bookDesign->design ?>
            <a class="design-block" style="background-image:url('/data/design-files/<?= $design->id ?>-164px.png')"
               href="<?= $this->url('show-design', array('id' => $design->id)) ?>"></a>
        <? endforeach ?>

        <? if (count($book->bookDesigns) == 0): ?>
            <div class="alert alert-warning">
                This book has no designs added yet!
                <a class="btn btn-sm btn-primary" style="margin-left: 10px" href="<?= $this->url('all-designs') ?>">Add Some Now</a>
            </div>
        <? endif ?>
    </div>
</div>
